-- 
-- Script was generated by Devart dbForge Schema Compare for PostgreSQL, Version 1.2.182.0
-- Product Home Page: http://www.devart.com/dbforge/postgresql/schemacompare
-- Script date 10/23/2022 1:50:52 AM
-- Source server version: 13.5
-- Source connection string: User Id=postgres;Host=localhost;Port=5432;Database=development;Unicode=True;Connection Timeout=15;Default Command Timeout=0;Integrated Security=False
-- Target server version: 13.5
-- Target connection string: User Id=postgres;Host=localhost;Port=5432;Database=production;Unicode=True;Connection Timeout=15;Default Command Timeout=0;Integrated Security=False
-- Run this script against production to synchronize it with development
-- 

--
-- Drop column "name" from table "public"."attendee"
--
ALTER TABLE public.attendee 
  DROP COLUMN name;

--
-- Create column "first_name" on table "public"."attendee"
--
ALTER TABLE public.attendee 
  ADD first_name text;

--
-- Create column "last_name" on table "public"."attendee"
--
ALTER TABLE public.attendee 
  ADD last_name text;